// General MIDI instrument kit as SoundBox 29-number `i` arrays.
//
// The 16 melodic family patches (`program >> 3` selects one) and 8 drum patches
// are generated by the soundbox-fit tool from subtractive-synth recipes tuned
// against tinysynth GM references — see kit.generated.js. The extra percussion
// patches below (rimshot, clap, toms, tambourine, ...) are still hand-authored
// first-pass values. `percForNote()` routes GM notes 35..81 to a patch.

import { MELODIC as GEN_MELODIC, PERCUSSION as GEN_PERCUSSION } from "./kit.generated.js";

export const MELODIC = GEN_MELODIC;

// GM melodic families, index 0..15 == program >> 3.
export const GM_FAMILY = [
  "piano",
  "chromperc",
  "organ",
  "guitar",
  "bass",
  "strings",
  "ensemble",
  "brass",
  "reed",
  "pipe",
  "synthLead",
  "synthPad",
  "synthFx",
  "ethnic",
  "percussive",
  "sfx",
];

// Generated drum patches, plus still-hand-authored ones for the drums the
// generator doesn't cover yet. `percForNote()` maps notes to these keys.
export const PERCUSSION = {
  ...GEN_PERCUSSION,
  tomLow: GEN_PERCUSSION.tomLo,
  tomHigh: GEN_PERCUSSION.tomHi,
  tomMid: GEN_PERCUSSION.tomLo,
  rimshot: [0, 120, 140, 40, 0, 0, 128, 0, 0, 150, 2, 4, 16, 190, 0, 0, 0, 0, 0, 0, 1, 180, 0, 0, 42, 0, 0, 0, 0],
  clap: [0, 0, 128, 0, 0, 0, 128, 0, 0, 220, 2, 6, 32, 95, 0, 0, 0, 0, 0, 0, 3, 150, 60, 0, 42, 0, 0, 0, 0],
  tambourine: [0, 0, 128, 0, 0, 0, 128, 0, 0, 170, 2, 5, 28, 75, 0, 0, 0, 0, 0, 0, 1, 210, 30, 0, 42, 0, 0, 0, 0],
  cowbell: [1, 150, 150, 0, 1, 120, 157, 0, 0, 0, 2, 6, 26, 120, 0, 0, 0, 0, 0, 0, 2, 160, 0, 0, 44, 0, 0, 0, 0],
  shaker: [0, 0, 128, 0, 0, 0, 128, 0, 0, 160, 2, 3, 16, 85, 0, 0, 0, 0, 0, 0, 1, 220, 0, 0, 40, 0, 0, 0, 0],
  woodblock: [0, 140, 150, 40, 0, 0, 128, 0, 0, 40, 2, 4, 18, 170, 0, 0, 0, 0, 0, 0, 2, 170, 0, 0, 44, 0, 0, 0, 0],
  conga: [0, 165, 126, 90, 0, 0, 128, 0, 0, 20, 2, 10, 34, 150, 0, 0, 0, 0, 0, 0, 2, 120, 0, 0, 44, 0, 0, 0, 0],
  triangle: [0, 120, 170, 0, 0, 90, 182, 0, 0, 0, 2, 6, 85, 30, 0, 0, 0, 0, 0, 0, 2, 180, 0, 0, 38, 0, 0, 50, 80],
};

// GM percussion note number (35..81) -> PERCUSSION key.
const PERC_NOTE = {
  35: "kick", 36: "kick", 37: "rimshot", 38: "snare", 39: "clap", 40: "snare",
  41: "tomLow", 42: "hatClosed", 43: "tomLow", 44: "hatClosed", 45: "tomMid",
  46: "hatOpen", 47: "tomMid", 48: "tomHigh", 49: "crash", 50: "tomHigh",
  51: "ride", 52: "crash", 53: "ride", 54: "tambourine", 55: "crash",
  56: "cowbell", 57: "crash", 58: "tambourine", 59: "ride",
  60: "conga", 61: "conga", 62: "conga", 63: "conga", 64: "conga",
  65: "tomMid", 66: "tomLow", 67: "cowbell", 68: "cowbell",
  69: "shaker", 70: "shaker", 71: "shaker", 72: "shaker",
  73: "shaker", 74: "shaker", 75: "woodblock", 76: "woodblock", 77: "woodblock",
  78: "shaker", 79: "shaker", 80: "triangle", 81: "triangle",
};

// Nearest defined percussion key for any note number.
export function percForNote(note) {
  if (PERC_NOTE[note]) return PERC_NOTE[note];
  let best = "snare";
  let bestDist = Infinity;
  for (const k of Object.keys(PERC_NOTE)) {
    const d = Math.abs(+k - note);
    if (d < bestDist) {
      bestDist = d;
      best = PERC_NOTE[k];
    }
  }
  return best;
}

export function melodicForProgram(program) {
  const p = Math.max(0, Math.min(127, program | 0));
  return GM_FAMILY[p >> 3];
}

// Neutral default when a voice names no program.
export const DEFAULT_MELODIC = "piano";
